#!/usr/bin/env python3
"""Build a deterministic repository manifest for Downfall.

Usage:
  python tools/repository/build_manifest.py
  python tools/repository/build_manifest.py --check
  python tools/repository/build_manifest.py --output PROJECT_MANIFEST.md
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = ROOT / "PROJECT_MANIFEST.md"

EXCLUDED_DIRS = {
    ".git", ".idea", ".vs", ".vscode", "Library", "Logs", "Temp",
    "obj", "Build", "Builds", "UserSettings", "node_modules", "__pycache__",
}
EXCLUDED_FILES = {"PROJECT_MANIFEST.md"}
TEXT_EXTENSIONS = {
    ".md", ".txt", ".cs", ".py", ".json", ".yaml", ".yml", ".xml",
    ".asmdef", ".cginc", ".shader", ".uss", ".uxml", ".gitignore",
}
CATEGORY_RULES = [
    ("Wiki", "Wiki/"),
    ("Runtime code", "Scripts/"),
    ("Tools", "tools/"),
    ("GitHub automation", ".github/"),
    ("Documentation", "docs/"),
]


def is_excluded(path: Path) -> bool:
    rel = path.relative_to(ROOT)
    if path.name in EXCLUDED_FILES:
        return True
    return any(part in EXCLUDED_DIRS for part in rel.parts)


def is_text_candidate(path: Path) -> bool:
    return path.suffix.lower() in TEXT_EXTENSIONS or path.name.startswith(".")


def classify(rel: str) -> str:
    for category, prefix in CATEGORY_RULES:
        if rel.startswith(prefix):
            return category
    return "Other"


def digest(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()[:12]


def collect() -> list[dict[str, object]]:
    records: list[dict[str, object]] = []
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file() or is_excluded(path):
            continue
        rel = path.relative_to(ROOT).as_posix()
        records.append({
            "path": rel,
            "category": classify(rel),
            "extension": path.suffix.lower() or "(none)",
            "size": path.stat().st_size,
            "text": is_text_candidate(path),
            "sha256": digest(path),
        })
    return records


def render(records: list[dict[str, object]]) -> str:
    by_category: dict[str, list[dict[str, object]]] = defaultdict(list)
    extension_counts = Counter(str(r["extension"]) for r in records)
    text_count = sum(1 for r in records if r["text"])

    for record in records:
        by_category[str(record["category"])].append(record)

    lines = [
        "# Downfall Project Manifest",
        "",
        "> Auto-generated by `tools/repository/build_manifest.py`. Do not edit the generated inventory by hand.",
        "",
        "## Repository summary",
        "",
        f"- Total tracked candidates: {len(records)}",
        f"- Text/config candidates: {text_count}",
        f"- Binary/other candidates: {len(records) - text_count}",
        "",
        "## Category summary",
        "",
        "| Category | Files |",
        "|---|---:|",
    ]

    for category in sorted(by_category):
        lines.append(f"| {category} | {len(by_category[category])} |")

    lines.extend([
        "",
        "## Extension summary",
        "",
        "| Extension | Files |",
        "|---|---:|",
    ])
    for ext, count in sorted(extension_counts.items(), key=lambda item: (-item[1], item[0])):
        lines.append(f"| `{ext}` | {count} |")

    lines.extend(["", "## File inventory", ""])
    for category in sorted(by_category):
        lines.append(f"### {category}")
        lines.append("")
        lines.append("| Path | Size | Kind | SHA-256 |")
        lines.append("|---|---:|---|---|")
        for record in by_category[category]:
            kind = "text/config" if record["text"] else "binary/other"
            lines.append(
                f"| `{record['path']}` | {record['size']} | {kind} | `{record['sha256']}` |"
            )
        lines.append("")

    lines.extend([
        "## Management notes",
        "",
        "- Wiki document metadata is indexed separately in `Wiki/00_System/Wiki_Index.md`.",
        "- This manifest inventories files; it does not prove runtime usage or Unity reference integrity.",
        "- Files classified as binary/other require separate Unity, Git LFS, or asset-level review.",
        "- Removal candidates must be reference-searched and approved before deletion.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Downfall project manifest.")
    parser.add_argument("--check", action="store_true", help="Exit non-zero if the manifest is stale.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    output_path = args.output if args.output.is_absolute() else ROOT / args.output
    generated = render(collect())

    if args.check:
        if not output_path.exists():
            print(f"ERROR: manifest not found: {output_path}", file=sys.stderr)
            return 1
        current = output_path.read_text(encoding="utf-8")
        if current != generated:
            print("ERROR: PROJECT_MANIFEST.md is stale. Run build_manifest.py.", file=sys.stderr)
            return 1
        print("OK: PROJECT_MANIFEST.md is current.")
        return 0

    output_path.write_text(generated, encoding="utf-8")
    print(f"Wrote {output_path.relative_to(ROOT)} with {len(collect())} files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
